### ISSUE TITLE
More forgiving format matching

### ISSUE THREAD

**Issue by Scarletsang** [nafuka11/philosophers-visualizer#37]
The regex and forkregex should be something like this:
`^\d+\s+\d+\s+has taken a fork$`

This allows arbitary amount of space to be added between the status and the id of the philosopher.

**Comment by nafuka11** [comment]
Thank you for raising an issue! 
I've implemented the suggested improvements in #38. 
While I believe the issue has been addressed, if you find any problems, please don't hesitate to reopen the issue!
